### ISSUE TITLE
Reindexing seems to have stopped

### ISSUE THREAD

**Issue by buchner** [jirkapinkas/javalibs#12]
The web site states that reindexing should happens twice a week. According to what is shown on the page the last reindexing happened 2020-09-13. This seems not to be only a displaying issue. I recently published my project to maven central. I can find it there but I can not find it via javalibs.

**Comment by jirkapinkas** [comment]
Hi. Yes, currently reindexing doesn't work (online is quite old snapshot), because due to pandemic I need full bandwidth during weekdays, so it's a little bit more complicated to perform reindexing so that it doesn't affect my day job. Sorry for the inconvenience. During this weekend newer snapshot should by synced, but still it will be one or two weeks old (because three - four weeks ago I was fighting COVID and during that time one operation failed, required manual intervention and that's the ultimate cause why there's this delay in the first place).

**Comment by buchner** [comment]
Hi. Thank you for your fast response. Sorry to hear about your situation. Hope you had a full recovery.

**Comment by jirkapinkas** [comment]
Thankfully I'm completely fine now. Yesterday sync of older snapshot was performed and as promised in a few days everything will be up-to-date.
