### ISSUE TITLE
JavaLibs stopped refreshing versions

### ISSUE THREAD

**Issue by FilipJirsak** [jirkapinkas/javalibs#8]
It seems javalibs stopped refreshing new versions of artifacts from the Maven central repository. For example I have found the following old versions:
* org.flywaydb:flyway-core:5.1.4 → current is 5.2.0
* com.fasterxml.jackson.core:jackson-core:2.9.6 → curent is 2.9.7
* org.junit.jupiter:junit-jupiter-api:5.3.0-RC1 → current is 5.3.1
* javax.json:javax.json-api:1.1.2 → current is 1.1.3

**Comment by jirkapinkas** [comment]
Hello Filip,

unfortunately because I've been scraping Central (for a few years) :-), the traffic was noticed and my IP address was finally blocked. Right now I'm negotiating with Sonatype a legal way for javalibs to operate. Refreshing will be resumed once it's resolved (hopefully within several days). In the meantime you can click on "see this artifact on: search.maven.org" link, which is at every artifact's page to see the latest version.

I'm really sorry for the inconvenience.

When it's resolved, I'll post a comment here to let you know.

Jirka

**Comment by cestpraci** [comment]
Hi Jirko,
do you have any progress on updating your repository based on current data from maven.org?

Thank you in advance
Petr

**Comment by jirkapinkas** [comment]
Hi Petr,

deal with Sonatype is still a work in progress, but I started indexing again and within couple of days it will work as before (unfortunately there's lots of data to process because it wasn't running for several months). :-(
